### PR TITLE
fix compatibility issue with pydantic 2.0+

### PR DESCRIPTION
**Pull request by fredi-python**
https://discord.com/channels/1104020730678612001/1129974705441476672/1186742881310998560

tested locally, works just fine now

### CODE REVIEW

**Comment by azuruce** [comment]
can you change title to fix compatibility issue with pydantic 2.0+?

**Comment by fredi-python** [comment]
> can you change title to fix compatibility issue with pydantic 2.0+?

done

**Comment by alexandred** [comment]
HI Fredi,

Thanks for your PR! We've recently added in some workflows to make it easier to manage the repos. Could you please bring your fork up to date with master, so that we can merge?

**Comment by fredi-python** [comment]
@alexandred Done :heavy_check_mark:

**Review by alexandred — APPROVED** [review]

**Pull request merged**
